name: Run Portis Script

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        node-version: '20'  # Specify Node.js version 20

    - name: Install Pandoc
      run: sudo apt-get install -y pandoc

    - name: Run Portis Script
      run: ./portis.sh
