name: Run Portis Script

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository 
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install Pandoc
      run: sudo apt-get install -y pandoc

    - name: Check Pandoc version
      run: pandoc --version

    - name: Run Portis Script
      run: ./portis.sh
